#!/bin/sh

# Redirection des logs Nginx vers la console Railway pour voir les erreurs
ln -sf /dev/stdout /var/log/nginx/access.log 2>/dev/null || true
ln -sf /dev/stderr /var/log/nginx/error.log 2>/dev/null || true

# Récupération du port dynamique fourni par Railway (ou fallback sur 8080)
PORT_TO_USE="${PORT:-8080}"
echo "Port réseau actif : $PORT_TO_USE"

# Modification propre du fichier de configuration Nginx
sed -i -E "s/listen .*/listen 0.0.0.0:$PORT_TO_USE;/g" /etc/nginx/conf.d/default.conf 2>/dev/null || true
sed -i -E "s/listen .*/listen 0.0.0.0:$PORT_TO_USE;/g" /etc/nginx/nginx.conf 2>/dev/null || true

# Lancement de PHP-FPM
php-fpm -D

# Verification et Lancement Nginx
nginx -t && exec nginx -g 'daemon off;'
